### ISSUE TITLE
mysql.replication.checksum[] error

### ISSUE THREAD

**Issue by okand** [m4ce/zabbix-mysql#6]
Hello.

Zabbix-agent version: 3.4.7

I get the following error on every autodiscovered replicated database/table.

```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
/etc/zabbix/scripts/mysql.sh: line 369: [: too many arguments
/etc/zabbix/scripts/mysql.sh: line 381: [: too many arguments
1" of type "string" is not suitable for value type "Numeric (float)"
```

I've tried quoting the variables or changing to double brackets on those two lines but that's not done anything really. The error becomes this instead
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
/etc/zabbix/scripts/mysql.sh: line 369: [: Checksum
0: integer expression expected
/etc/zabbix/scripts/mysql.sh: line 381: [: Checksum
0: integer expression expected
1" of type "string" is not suitable for value type "Numeric (float)"
```

Everything else works well though and I could just settle for monitoring the replication status thingy and not bother comparing checksums. Thanks for writing this thing.

**Comment by m4ce** [comment]
@okand , can you maybe print out the value of the master and slave checksums at line 369 and 381. That'd help.

**Comment by okand** [comment]
I found the `--verbose` option. Apologies for missing that at first.

The checksums varies, some are just 0, others are longer numbers. Some match, some don't. But they all then get the error anyway.


I made this one different on purpose.
__mysql.replication.checksum[repltest.testtable]__
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
master_checksum: Checksum
2485354515
slave_checksum: Checksum
2273413212
/etc/zabbix/scripts/mysql.sh: line 369: [: too many arguments
/etc/zabbix/scripts/mysql.sh: line 381: [: too many arguments
1" of type "string" is not suitable for value type "Numeric (float)"
```

Then I removed the duplicate id and ran `start slave;` to fix it.
__mysql.replication.checksum[repltest.testtable]__
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
master_checksum: Checksum
2485354515
slave_checksum: Checksum
2485354515
/etc/zabbix/scripts/mysql.sh: line 369: [: too many arguments
/etc/zabbix/scripts/mysql.sh: line 381: [: too many arguments
1" of type "string" is not suitable for value type "Numeric (float)"
```

I'm new to mysql replication itself so maybe I've just configured that wrong? It's a brand new install with nothing in yet except the databases that are there by default and one really tiny one I made to test with.
I didn't configure `binlog_do_db` at all thinking that would just replicate everything which it appears to have done. Is it bad to replicate `information_schema`, `mysql`, `performance_schema` and `sys`? They all show up as items on my slave hosts when I view items without data having the errors above.

I am running zabbix-agent and therefore also this script as the user zabbix instead of root like in the example in the readme. Therefore the users shell is `/bin/false` unlike root which has `/bin/bash`. Maybe that affects how the script runs in some way?

**Comment by m4ce** [comment]
Can you make sure you do `echo "|${master_checksum}|"` and `echo "|${slave_checksum}|"`. I just want to check that there are no spaces in there.

**Comment by m4ce** [comment]
Also, which version of MySQL are you running?

**Comment by m4ce** [comment]
I've just pushed a branch (`issues/6`). Try using that and let me know if it fixes your issue.

**Comment by okand** [comment]
Mysql version:
```
root@api01:~# mysql --version
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
```
It's the default in Ubuntu 16.04 from running `apt install mysql-server`.

I replaced mysql.sh and mysql_helpers.sh with the new branch versions. Now the red error box for each item looks like this instead:
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
master_checksum: |0|
slave_checksum: |0|
0" of type "string" is not suitable for value type "Numeric (float)"
```

Edit:
Or like this:
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
master_checksum: |2485354515|
slave_checksum: |2485354515|
0" of type "string" is not suitable for value type "Numeric (float)"
```

**Comment by okand** [comment]
One that doesn't match looks like this instead:
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
master_checksum: |2225557806|
slave_checksum: |1130710548|
retrying (1/3)
mysql: [Warning] Using a password on the command line interface can be insecure.
master_checksum: |2225557806|
slave_checksum: |1130710548|
retrying (2/3)
mysql: [Warning] Using a password on the command line interface can be insecure.
master_checksum: |2225557806|
slave_checksum: |1130710548|
retrying (3/3)
1" of type "string" is not suitable for value type "Numeric (float)"
```

It looks like it is working and I should just remove `--verbose` from the userparameter in my zabbix-agent config and maybe also do something about that password warning then?

**Comment by m4ce** [comment]
cool - if you remove the --verbose, do you still get the `1" of type "string" is not suitable for value type "Numeric (float)"` error?

**Comment by m4ce** [comment]
I just pushed another change to the `mysql_helpers.sh` into the branch. Try that out.

**Comment by okand** [comment]
The newest branch where the error is redirected to /dev/null is working!


Just removing `--verbose` on the old version still gave me the zabbix error.
Like this:
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
0" of type "string" is not suitable for value type "Numeric (float)"
```
 Or like this, repeated as many times as the checksum check is repeated when it fails:
```
Value "mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
1" of type "string" is not suitable for value type "Numeric (float)"
```

**Comment by m4ce** [comment]
alright, so I guess we can close it. Redirecting stderr to /dev/null is not ideal. It looks like zabbix agent has changed and it's now reading that in. Zabbix used to ignore stderr and only log that to the agent's log file. I will merge the PR and you can revert to use master.
